### ISSUE TITLE
Inefficient Computation of MDSC due to inverse matrix

### ISSUE THREAD

**Issue by LeoGitGuy** [Yuanyuan-Yuan/NeuraL-Coverage#3]
Hello,

first of all, thanks for the great repo and all the coverage implementations. I want to use the implementation of "MDSC" for a research project and it was incredibly slow. I found out that this is mainly due to the following code:

```
def calculate(self, data_batch, label_batch):
    [...]
    mu = self.estimator.Ave[label_batch]
    covar = self.estimator.CoVariance[label_batch]
    covar_inv = torch.linalg.inv(covar)
```  
in file "coverage.py".

Shouldn't it be possible to precompute the inverse of the Covariance matrix for each class in the build step and save it instead of recomputing it every time in the calculation step? I think this would save loads of time.
If you agree I will gladly create a pull request.

Best, Leo

**Comment by ooorin** [comment]
@LeoGitGuy  Hi Leo,

Thank you for the issue. Yes, precomputing the inverse of the covariance matrix can save some time.
If you can create a pull request, I'd like to merge it into the repo. Thank you very much!

Best,
Yuanyuan

**Comment by LeoGitGuy** [comment]
Thanks for your reply @ooorin , I made a pull request which includes some other minor issues I encountered when running the code, like typecasting for some hyperparams or a missing "self" in the build method. I hope that is alright, otherwise I could create a seperate issue and pull request for this. 
Best, Leo

**Comment by ooorin** [comment]
@LeoGitGuy  Hi Leo,

I have merged the pull request. Thank you very much!

Best,
Yuanyuan
